image: maven:latest


stages:          # List of stages for jobs, and their order of execution
  - build
  - package


cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"


build-job:     
  image: maven:latest
  stage: build
  tags:
    - gitlab-org
  script:
    - mvn clean compile
  only:
    - main
    - merge_requests
  artifacts:
    paths:
      - target/*.jar

package :
  image: maven:latest
  stage: package
  tags:
    - gitlab-org
  script:
    - mvn package
  only:
    - main
  



